README.md, cli.js, examples/plugin-with-options.js, examples/plugin.js, help.txt, test.js
As titled, usage:
`$ fastify -o plugin.js`
```js
'use strict'
module.exports = function (fastify, options, next) {
fastify.get('/', function (req, reply) {
reply.send({ hello: 'world' })
})
next()
}
module.exports.options = {
https: {
key: 'key',
cert: 'cert'
}
}
```
=> Custom options support

cli.js, help.txt, package.json
This pr is to prepare the direct integration of the cli with Fastify, once we approve this I'll update Fastify by adding the following code to the `package.json`:
```json
"bin": {
"fastify": "./node_modules/.bin/fastify"
},
```
In this way the users can use the cli out of the box.
What is inside this pr:
- Added pretty logs with [pino-colada](https://github.com/lrlna/pino-colada)
- Added [address](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#listen) option
- Added [update notifier](https://github.com/yeoman/update-notifier) for fastify
=> Pretty logs, address option, update notifier

.gitignore, .travis.yml, cli.js
So that in fastify we could have our own binary that just requires this and calls `cli()`.
The current approach we are using does not work on npm@5.
=> Export cli() so that we can call it from fastify

README.md, cli.js, help.txt, package.json, test.js
Refactorize in order to return fastify instance. So the test can start and stop the instance and run multiple tests.
Add `prefix` command line parameter
=> Add prefix. Refactor to run multiple tests

cli.js, examples/incorrect-plugin.js, test.js
Closes https://github.com/fastify/fastify/issues/262 
Checks the length of the function arguments in the plugin file. Throws an error if 3 are not provided.
=> Added argument length checker

README.md, cli.js, examples/async-await-plugin.js, package.json, test.js
Addressing #16, I added a test to check the CLI against an async/await plugin, then I added the related example both in README and in the proper directory. I used fastify 0.30.2 to ensure I was working with the very last version of the framework, is it ok?
I had to rework the arity check too, I dont know if it's ok for you.
=> Add async/await plugin support

README.md, cli.js, package.json
This causes fastify to be installed as a dependency of fastify-cli, as
fastify will no longer provide a command-line utility.
See fastify/fastify#514 for discussion.
=> Move fastify from devDependency to dependency.

README.md, cli.js, examples/plugin.js, help.txt, test.js
As requested by myself in #43, I added support for [`bodyLimit` parameter](https://github.com/fastify/fastify/blob/master/docs/Factory.md#bodylimit) passed to the fastify factory through the `--body-limit` option. No default value is set, since fastify has already its default value.
I added the keyword `body-limit` to the `minimist` options in the `integer` array, for coherency, even though `minimist` does not do anything at all with the `integer` key (as we can see from [its documentation](https://github.com/substack/minimist#var-argv--parseargsargs-opts))
Does it have any sense for the `integer` key to exists in the `minimist` options?
=> Add bodyLimit support through --body-limit option

README.md, app_template/services/README.md, generate.js, test/generate.js
I've updated the script section:
- Now the test runner path is `test/*.test.js test/**/*.test.js test/**/**/*.test.js`, because it can happen that a user writes some test in a deeper folder,  `/test/services/example/example.test.js` for example.
- Renamed `colada` to `dev`, is more clear the idea of the script and less criptic for the one who does not know `pino-colada`.
- Added `lint`, which basically is `standard --fix`.
I've also updated some part of the documentation and added a small summary of what `fastify generate` will build.
=> Update scripts and docs

app_template/app.js
I'm not super convinced about this. Maybe we should rename `dir` to `autoload: { dir }` to avoid namespace clashing.
What do you think?
=> Pass options down to the autoloaded plugins

README.md, help/start.txt, package.json, start.js, test/data/timeout-plugin.js, test/start.js
This sets the default timeout to 10 seconds.
=> plugin timeout support

README.md
Fixes https://github.com/fastify/fastify-cli/issues/85.
=> Create docs on how to migrate off fastify-cli start

README.md
When i follow the instruction i get error:
```
ReferenceError: fastify is not defined
```
The right reference is the `app`, isn't it?
Here is the working snippet:
```
// Register your application as a normal plugin.
app.register(require('./app.js'))
// Start listening.
app.listen(process.env.PORT || 3000, (err) => {
if (err) {
app.log.error(err)
process.exit(1)
}
})
```
=> Fix docs on how to migrating out of fastify-cli start (#104)

generate.js, package.json, start.js, test/start.js
Swapped minimist with yargs-parser because works better with prefixed env variables and is currently maintained.
This move will fix issue #110.
=> Fix boolean env variables override

test/cli.test.js, test/generate.test.js
Previously, I sent a PR to `generify` to use environment eol (https://github.com/mcollina/generify/blob/master/generify.js#L69).
Now that we normalized all line endings (yes I stupidly pushed attributes file to origin to force normalize endings), the template in `fastify-cli` and the generated files differ in windows environment. 
So we either should normalize line endings here in tests via regexp or patch generify to not touch line endings.
I think the approach in this PR should be fine
=> Normalize line endings in tests

generate.js, help/generate.txt, test/generate.test.js
Change `<folder>` as a required param.
When I use `fastify generate` it will create files in current dir. It's ok when I am in the right dir, but It will waste time to delete files which generate created in the wrong dir.  
I thought it is necessary to make `<folder>` to be required, or add a tips in `fastify help` not just in `fastify help generate`
=> generate <folder> change

start.js, test/start.test.js
Fixes #181
Shows up a warning rather than throwing the error.
=> chore: warns the user appropriately for non-existent files

templates/app/__gitignore
Open source libs can benefit from ignoring lock files, but apps should commit them to source control.
=> Remove lock files from app template .gitignore

cli.js, help/help.txt, help/print-routes.txt, print-routes.js, start.js, test/print-routes.test.js, test/start.test.js, util.js
Hello,
I found myself needing a way to see a list (or tree) breakdown of all the routes my project had and thought it might be useful to have a command in `fastify-cli` that does just that.
This is essentially a CLI wrapper for `fastify.printRoutes`.
It behaves similarly to `fastify start` command except it relies on `fastify.ready()` rather than `fastify.listen()`, as such, there are a few function that are identical in both commands and could probably be abstracted and reused. If it seems reasonable, I could do it in the same PR. 
The reason I didn't write these abstractions is I preferred not to introduce too many changes to the project structure in order not to make this PR too invasive.
=> Add command to print routes

.gitignore, README.md, args.js, lib/watch/index.js, start.js, test/args.test.js, test/start.test.js
With this PR you should be able to run a FastifyCLI-generated app with NodeJS inspector on a chosen port. The added flags are: `-d` (`--debug`) for enabling the debug mode and `-I` (`--debug-port`) for choosing a debug port. Works even in `--watch` mode.
- Programmatically call `inspector.open` right before running Fastify for the current process when debug mode active. Refs: https://nodejs.org/api/inspector.html
- Updated readme.md documentation
This PR was created referring this issue: https://github.com/fastify/fastify-cli/issues/200. Thanks also to @pyxarez and @xtx1130. Feel free to contribute.
- [-] run `npm run test` and `npm run benchmark`
- [-] tests and/or benchmarks are included
- [-] documentation is changed or added
- [-] commit message and code follows [Code of …
=> Debug mode for Fastify CLI Start

package.json, test/start.test.js
ref #202 , add test cases for that pr.
=> test: add test cases for inspect

generate.js, test/generate.test.js
Wouldn't it makes sense to add the `-watch` option to the dev task?
=> Add -watch option to dev task

README.md, args.js, start.js, test/args.test.js
This PR allows specifying a debug host using the `--debug-host=x.x.x.x` argument. In addition, when the debug mode is started inside a docker container, the debug host will be automatically set to `0.0.0.0` unless specified otherwise.
=> Add ability to specify the debug host

README.md, cli.js, docs.js, help/docs.txt, help/help.txt, package.json
This PR adds the ability for you to view the documentation for fastify in your terminal. By default, `fastify-cli` attempts to render the documentation for the fastify version installed in the current working directory node_modules folder, however, if none are found, it should fall back to rendering the documentation for the version that fastify-cli depends on.
The documentation is rendered using an interactive terminal session that you can navigate with your arrow keys.
run `fastify docs` to get started.
Screenshots:
=> add command to render interactive docs to the terminal

README.md, args.js, examples/plugin-with-custom-options.js, examples/ts-plugin-with-custom-options.js, help/start.txt, package.json, start.js, test/args.test.js, test/start.test.js
Allow passing custom options for the app plugin using additional arguments from the cli. All the args passed after `--` will be parsed and passed to the plugin as options.
Fixes #240 .
=> feat: pass custom plugin options from cli

README.md, args.js, test/args.test.js
Added .swp files to the list of default values to ignore-watch for
=> update ignore-watch default values with .swp files

.gitignore, args.js, examples/plugin.ts, generate.js, lib/watch/tsc-watcher.js, start.js, templates/app-ts/src/routes/example/index.ts, templates/app-ts/tsconfig.json, test/args.test.js, test/generate-typescript.test.js, test/start-typescript.test.js, test/start.test.js, test/util.js, tsconfig.json, tsconfig.tswatch.json
The idea is that we should make the user run `fastify start...` on .ts files and watch for changes on those files.
At the moment the `npm run dev` script in ts project template uses `concurrently` so we basically have 2 watchers running together: one for ts files and one for the compiled `dist` files.
This is not ideal.
This approach uses only the tsc API to watch for .ts files changes. Every time it detects a change it kills fastify process, re-compiles changed files, restarts fastify.
Note: for the moment I assumed that if the target file is a .ts file we always want to watch it even without `-w` option.
Note: [docs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-
Any suggestion …
=> feat: start can now watch ts files (#246)

templates/app-ts/src/plugins/README.md, templates/app/plugins/README.md, templates/app/routes/README.md
Found a couple dead links and figured it was better to match the rest of the READMEs and link to fastify.io documentation instead of github.
=> Update doc links in template READMEs to point to fastify.io

.gitignore, test/data/async-plugin-with-one-argument.js, test/start.test.js, util.js
Error was being returned, leading to a misleading error displayed when starting the plugin using fastify-cli.
=> fix: should throw error when async plugin is invalid

README.md, help/generate.txt
Hi 👋 Thanks for the awesome CLI!
I want to gen a TS project and noticed there is a `templates/app-ts` template in this project.
But I run through `README.md` and there no info about it. Even I run `fastify help generate` still so.
So I add a little info to help cmd & README.md. Please let me know if I need to correct any mistakes or omissions.
Thank you!
=> docs(help/generate.txt, readme): add generate command typescript template info

README.md, help/generate-plugin.txt, help/help.txt, package.json
Issue #295 
I updated `help-me` because v2.0.0 allows 2 files having common prefix (`generate` and `generate-plugin`) to work if the user inserts the complete name. (https://github.com/mcollina/help-me/pull/3)
=> fix: help command now prints generate-plugin info

eject-ts.js, eject.js, test/eject-ts.test.js, test/eject.test.js
Fixes the eject and eject-ts tests and implementation
=> Fix eject and eject-ts tests

README.md, args.js, examples/plugin-with-preloaded.js, help/start.txt, start.js, test/args.test.js, test/data/custom-require.js, test/data/custom-require2.js, test/start.test.js, util.js
As described in #314.
Some notes:
- `-r` option was already in use for `prefix` so took `b`/`before-module` (like existing `logging-module` option). Feel free to request other naming if preferred.
- Requiring the actual module seemed exactly the same as the existing `logging-module`. In an effort to create a function out of it, I abstracted the core part of `util.js's` `requireServerPluginFromPath` to `requireModule`. This leads to some minor differences in textual error output. Behavior of when errors are thrown is still the same though.
=> Add option to load module before anything else #314

README.md
`fastify-cli` is really cool! I want to use esnext with no build step for my current project, and was glad to find that fastify-cli has no conflict with node's new ability to run es modules with a `.js` extension when `"type": "module"` is set in package.json
=> Change .mjs to .js and add note about "type": "module"

lib/watch/index.js, start.js, test/start.test.js
Fixes #327 
This change makes `fastify start` work for both scenarios:
1. using FASTIFY_* env vars from `.env` file, e.g. `FASTIFY_WATCH`
2. support reloading after `.env` file change in watch mode so that the app sees the updated env vars
- the version before #300 was loading `.env` at `start.js` module initialization, thereby supporting only case 1) and not case 2) because even if the module is reloaded within the same process, dotenv doesn't overwrite env vars which are already set
- the version after #300 was loading `.env` too late, thereby supporting only case 2) but not case 1)
- an automated test, which is not straightforward to write
- `cd examples`
- add `FASTIFY_WATCH=true` to `.env`
- `node ../cli.js start plugin-with-env.js` (note we're not providing `-w`)
- see that changing …
=> fix: make both fastify and plugin env vars work

generate.js, test/generate-typescript.test.js
This patch was included as a comment [here](https://github.com/fastify/fastify-cli/issues/246#issuecomment-700819896), it should be included in the template and be like that out of the box.
Without this change we have a weird behavior between the typescript watcher and the CLI watcher.
CLI watcher basically restart before the TS compiler finishes its job so the changes are not visible immediately.
=> fix: watcher ignores ts files in typescript projects

generate.js, package.json, test/generate-typescript.test.js
`TS_NODE_FILES` set `true` so as to load `include` on startup.
#354 
=> Add TS Node environment variable

start.js, test/start.test.js, util.js
* Tries to fix #357 by leaving the current logic intact
* First checks if the provided module name is an existing file - if not - just use `require(id)`
=> allow preloading modules without referencing by filename

templates/app-ts/test/helper.ts, templates/app-ts/test/routes/root.test.ts, templates/app/test/helper.js, templates/app/test/routes/root.test.js, templates/plugin/test/index.test.js, test/args.test.js, test/eject-ts.test.js, test/eject.test.js, test/generate-plugin.test.js, test/generate-typescript.test.js, test/generate.test.js, test/graceful-shutdown.test.js, test/print-routes.test.js, test/start.test.js, test/templates/app-ts.test.ts, test/watch.test.js
* Tries to resolve all tap assertion deprecations in fastify-cli repo + templates
* Made a quick test with `node ./generate.js --lang=ts`  and `node ./generate.js`
* Path the way to a Tap upgrade maybe
=> fix all test deprecations

test/start.test.js
Skip one test on GitHub CI. Same tests consistently succeeds locally. It seems other tests have had the same problem over time and are already skipped.
=> fix: skip watch test on github ci

docs.js
I can navigate the left-bar files to read documentation, without triggering any errors
When I run `fastify docs` for my project, it lists an entry `resources` at the end of the list which is apparently a directory:
Clicking on this `resources` entry triggers an exception:
The list of files is generated as part of the logic that checks whether an entry is a filename to retrieve its content.
=> fix: only list files on the left-side navbar

templates/app-ts/README.md, templates/app/README.md, test/generate-typescript.test.js, test/generate.test.js
Closes #362 
This PR took me a whole day to debug. There is something wrong with tests, maybe with a specific npm package.
When adding a `README.md` template in `app` and `app-ts` like following
```
This project was bootstrapped with [Fastify-CLI](https://github.com/fastify/fastify-cli).
```
This results in the failure of test suitss. A workaround for this is to add content like the following:
```
```
=> Add default readme for generated project

generate.js, templates/app-ts/.vscode/launch.json, templates/app-ts/tsconfig.json, templates/app/.vscode/launch.json
I am proposing to add these changes to both JavaScript and TypeScript templates to allow code debugging in VSCode out of the box.
Following the request on this issue: https://github.com/fastify/fastify-cli/issues/426
- on this branch
- `node ./cli.js generate ../my-fastify-ts --lang ts` or `node ./cli.js generate ../my-fastify`
- `cd ../my-fastify-ts && npm install`
Now you should see the option "Launch Fastify" in the "Run and Debug" section of VSCode:
=> feat: config to debug TypeScript in vscode

.github/workflows/ci.yml, package.json, test/cli.test.js
Closes #492 
I'm not sure what happened with package help-me, but the version being used here in this repo is not the latest. It's a 3.x version which doesn't seem to work correctly, while 2.x works.
Running `node cli.js`:
1. without this fix
```
$ node cli.js
There are 8 help pages that matches the given request, please disambiguate:
* N:/nearform/fastify-cli/help/eject-ts
* N:/nearform/fastify-cli/help/eject
* N:/nearform/fastify-cli/help/generate-plugin
* N:/nearform/fastify-cli/help/generate
* N:/nearform/fastify-cli/help/help
* N:/nearform/fastify-cli/help/print-routes
* N:/nearform/fastify-cli/help/readme
* N:/nearform/fastify-cli/help/start
```
2. with this fix
```
$ node cli.js
Fastify command line interface available commands are:
* start                 start a server
* eject …
```
=> fix: downgrade help-me

.gitignore, README.md, args.js, generate.js, help/generate.txt, test/generate.test.js
resolves https://github.com/fastify/fastify-cli/issues/363
for typescript, see: https://github.com/fastify/fastify-cli/pull/512
=> feat: lint option for javascript template

templates/app/README.md
Removed the repeated non-hyperlinked `Fastify-CLI` from the header of the README.md of the generated template. This repetition doesn't occur at `app-ts` template (i.e., the TypeScript `fastify-cli` generated template)
=> Remove extra `Fastify-CLI` at template's `README.md`

README.md, examples/package-type-module/ESM-plugin-with-custom-server-options.js, test/start.test.js, util.js
=> feat: support exporting server options using `--options` on ESM

eject.js, test/eject-ts.test.js
Fixes a simple syntax error in `eject` where `argv` is not being called
=> fix: `argv` is callable

README.md, args.js, help/start.txt, start.js, templates/eject-ts/server.ts, templates/eject/server.js, test/args.test.js, test/data/custom-config.js
- Add use of .env FASTIFY_CLOSE_GRACE_DELAY for closeWithGrace in templates eject/server.js
- Add --close-grace-delay parameter
Related to Issue  #531
=> Add .env conf to graceful termination strategy suggested by templates

help/generate.txt, templates/app-esm/app.js, templates/app-esm/plugins/sensible.js, templates/app-esm/plugins/support.js, templates/app-esm/routes/example/index.js, templates/app-esm/routes/root.js, templates/app-esm/test/helper.js, templates/app-esm/test/plugins/support.test.js, templates/app-esm/test/routes/example.test.js, templates/app-esm/test/routes/root.test.js
For the ESM template:
* Removed 'use strict' since it is part of [ESM already ](https://262.ecma-international.org/6.0/#sec-strict-mode-code)
* Added help text for `--esm` option for generate command
=> Esm help text and removed use strict

package.json, templates/app-ts/test/helper.ts
=> Add test helper utility in TypeScript template

README.md, helper.js, start.js, test/helper.test.js
This addresses #546. I've decided to add a `serverOptions` parameter instead of using the `pluginOptions`. 
Added an example on how to enable logging during tap testing.
=> feat: added serverOptions to test helper.js

eject.js, help/eject.txt, templates/eject-esm/server.js, test/eject-esm.test.js, test/eject.test.js
- create template with server.js esm
- create test for esm
- improve test for non esm
- add help
Implementation for Issue #565 
=> create eject --esm command

lib/watch/index.js, test/start.test.js
=> fix: prevented .env values ​​from overwriting existing env values ​​when using --watch #558

.github/workflows/ci.yml, examples/plugin-with-logger.js, package.json, start.js, test/helper.test.js
requires https://github.com/fastify/deepmerge/pull/13
when the developer has a custom server option and needs to customize it when running the tests,  it is impossible to do it easily because the test options overwrite all the one set by the CLI arguments
=> fix: server config deep merge

README.md, start.js, test/start.test.js, util.js
This PR adds a check so that it automatically use 0.0.0.0 when running inside a Kubernetes environment.
=> fix: use address 0.0.0.0 in Kubernetes env (#579)

help/help.txt
As written, the help text says that a user can run `eject-ts` to create a standalone `server.ts`. However, this is incorrect. Doing so simply creates a `server.js` -- all text following `eject` is ignored. For instance, one could run `eject-foo` and get no error and have a `server.js` generated, even though there is no `eject-foo` command. 
Instead, a user must pass in the `lang` flag: https://github.com/fastify/fastify-cli/blob/426e359f65e51a054fa89117ce729f34f88a6c37/eject.js#L25-L26
The easiest way to update this help test looks to be to use the `ts` rather than `typescript` value for `--lang`, so that it can easily fit into the existing help text format.
=> fix: Correct wrong instructions for typescript ejecting

test/generate-esm.test.js
Fixed lint error.
```
$ npm run lint
> fastify-cli@5.7.1 lint
> standard
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
/Users/is2ei/src/github.com/is2ei/fastify-cli/test/generate-esm.test.js:36:36: ["c8"] is better written in dot notation. (dot-notation)
/Users/is2ei/src/github.com/is2ei/fastify-cli/test/generate-esm.test.js:36:67: ["c8"] is better written in dot notation. (dot-notation)
```
=> fix: use dot notation

README.md, args.js, cli.js, examples/plugin-common-prefix.js, help/help.txt, help/print-plugins.txt, help/print-routes.txt, package.json, print-plugins.js, print-routes.js, templates/app-ts-esm/__taprc, templates/app-ts/__taprc, test/args.test.js, test/print-plugins.test.js, test/print-routes.test.js, test/start.test.js
This adds a `method`, `common-prefix` and `include-hooks` flags to the `print-routes` command, and also implements a `print-plugins` flag, with no flags. 
- Closes https://github.com/fastify/fastify-cli/issues/636
- Closes https://github.com/fastify/fastify-cli/issues/635
Feedback wanted!
=> print-routes options and print-plugins

test/data/object.js, test/start.test.js, util.js
fixes: https://github.com/fastify/fastify-cli/issues/633
=> fix error on undefined plugin

generate-swagger.js, help/generate-swagger.txt, test/generate-swagger.test.js, test/swaggerplugindir/plugin.js
=> Add an option to generate YAML to generate-swagger

templates/app/app.js
Pass --options via CLI arguments in command have no effect
=> fix: app template options

package.json, templates/plugin/test/index.test-d.ts
This PR updates typescript version to v5 of this projects in order to work with the new changes.
Closes #670 
=> chore: update typescript version to v5

cli.js, eject.js, generate-plugin.js, generate-readme.js, generate.js, lib/watch/index.js, lib/watch/utils.js, start.js, templates/app/app.js, templates/app/test/helper.js, test/cli.test.js, test/eject-esm.test.js, test/eject-ts.test.js, test/eject.test.js, test/generate-esm.test.js, test/generate-plugin.test.js, test/generate-readme.test.js, test/generate-swagger.test.js, test/generate-typescript-esm.test.js, test/generate-typescript.test.js, test/generate.test.js, test/helper.test.js, test/start.test.js, util.js
See https://github.com/fastify/fastify-static/pull/407
=> perf: use `node:` prefix to bypass require.cache call for builtins

templates/app-esm/README.md, templates/app-esm/plugins/README.md, templates/app-esm/routes/README.md, templates/app-ts-esm/README.md, templates/app-ts-esm/src/plugins/README.md, templates/app-ts-esm/src/routes/README.md, templates/app-ts/README.md, templates/app-ts/src/plugins/README.md, templates/app-ts/src/routes/README.md, templates/app/README.md, templates/app/plugins/README.md, templates/app/routes/README.md, test/args.test.js, test/data/custom-config.js
See https://github.com/fastify/ajv-compiler/pull/115
=> chore: replace `fastify.io` links with `fastify.dev`

helper.d.ts
The call to `typeof` was missing so `build` type was incorrect and returned any.
=> Fix return type of build in helper

generate.js, test/generate-typescript.test.js
Fixes https://github.com/fastify/fastify-cli/issues/702
=> fix: add missing `c8` dev dependency

generate.js, test/generate-typescript.test.js
The demo can be found [here](https://github.com/adamward459/demo-fastify)
**Mac os**: 14.3.1 (23D60)
**Node**: v21.6.2
**Npm**: 10.2.4
List all tests under the test directory
```sh
➜  demo-fastify git:(main) find ./test -name "*.test.ts"
./test/plugins/support.test.ts
./test/routes/example.test.ts
./test/routes/root.test.ts
./test/routes/routes/example.test.ts
./test/routes/routes/root.test.ts
./test/routes/routes/routes/example.test.ts
./test/routes/routes/routes/root.test.ts
```
Run `test` command, the test command can only figure out files at first level.
```sh
➜  demo-fastify git:(main) npm test
> demo-fastify@1.0.0 test
> npm run build:ts && tsc -p test/tsconfig.json && c8 node --test -r …
```
=> Fix: Test script cannot detect test under test directory with deep level

README.md, generate-swagger.js, package.json, print-plugins.js, print-routes.js, start.js
make-promises-safe is not required in Node.js 15+. I presumed this would be non-breaking for fastify-cli because the test matrix is only 18, 20 & 21. I left in the tests that were added when make-promises-safe was added, and they continue to pass locally on Node.js 20 & 21. I have an issue with the tests in master hanging in Node 18, so couldn't confirm that certainly but there weren't any failures before the hang.
=> fix: make-promises-safe is no longer required

generate-plugin.js, generate.js, test/generate-esm.test.js, test/generate-plugin.test.js, test/generate-typescript-esm.test.js, test/generate-typescript.test.js, test/generate.test.js
=> feat(generate): add note about --integrate to package.json exists error

README.md, args.js, examples/plugin-with-preloaded.js, help/start.txt, start.js, test/args.test.js, test/data/custom-import.mjs, test/data/custom-import2.mjs, test/start.test.js, util.js
This PR adds support for preloading ES modules with the `--import` flag.  Related issue discussed in #671 
=> feat: add support for preloading ES module with --import flag

README.md, examples/plugin-with-custom-options.js, examples/ts-plugin-with-custom-options.js, examples/ts-plugin-with-custom-options.mjs, start.js, test/start.test.js
The TS typings and docs strongly imply that the `options` object defined in the app.js file should make their way to the app plugin if the `--options` cli argument is present when running `fastify start app.js`. This fix does just that, providing the exported options object back to the app plugin when it is registered.
The CLI allows arguments to make their way to the app via additional args (coming after a `--`), eg: `fastify start app.js -l info -- --custom test` will populate the plugin `options` argument with a `custom: "test"` property. This change deliberately leaves precedence with the CLI args so that the exported `options` object just forms the default values which can then be overridden as required.
Potential fix to #593 
and the [Code of …
=> fix: ensure `options` are passed to app plugin with `--options` flag

README.md, helper.d.ts
The third parameter of `build` is missing in the type declaration file, preventing users from passing the third parameter.
This PR also renames the parameters in the doc to align with the parameter names in `helper.js`.
=> fix: add missing parameter for type of `build` function in `fastify-cli/helper`

README.md, templates/app-ts-esm/__taprc, templates/app-ts/__taprc
Hi guys,
I'm recently playing with a new project and mentioned that you migrated from `tap` to `node:assert`, but `.taprc` is still in place.
This PR just removes unnecessary `__taprc` files from templates.
Thank you! 
=> chore(templates): remove obsolete .taprc file

templates/app-esm/routes/README.md, templates/app-ts-esm/src/routes/README.md, templates/app-ts/src/app.ts, templates/app-ts/src/routes/README.md, templates/app/routes/README.md
See https://github.com/fastify/demo/pull/1/files/243b2e0218c00cb9cf3cb95b84aa6dfe94dd7f79#r1632827244
=> docs: Emphasizing the monolythic approach in generated plugin README

helper.d.ts, helper.js, start.js, templates/app-ts/test/helper.ts, test/helper.test.js
=> fix: should ensure can access all decorators from app built with `helper.build`

start.js, templates/plugin/index.d.ts, test/data/custom-logger.mjs, test/start.test.js, util.js
Fixes #760 
~~I also want to add support for taking the logger from the main plugin module instead, in the same way you can specify an options object as a named export on it when giving the `--options` flag. But I haven't decided on how to name the CLI flag and if it should have a short single letter alias. Any suggestions?~~ &ndash; This already exists as `options.logger` with `--options` enabled. But there is an issue with `deepmerge` and passing an already created `pino.Logger`.
=> feat: Support ESM logging module

README.md, args.js, start.js, test/args.test.js
This adds support for the `trustProxy` option. Since that option can take many different forms I added 3 new arguments based on the conversation I saw on a similar PR that was closed.
https://github.com/fastify/fastify-cli/pull/654
=> add support for trustProxy option
