fastify/fastify-cli

package.json
Closes #6
https://greenkeeper.io/
=> fix(package): update fastify to version 0.17.0

.gitignore, README.md, cli.js, help.txt, package.json, test.js
Add socket option.
Add `pre-commit` package as devDependency
=> Socket listen

package.json
=> Update to ^0.39.1

README.md, README.tmpl, package.json
Add script to keep the README updated with `help.txt` file
=> Add generate-readme script

package.json
=> fix(package): update fastify to version 0.42.0

package.json, start.js, test/start.js
=> added automatic bind to 0.0.0.0 when running in docker

generate.js, test/generate.js
=> fix: make generate work with yarn

README.md, help/start.txt
=> --prefix shorthand is -r

generate.js, test/generate.js
=> fix (generate): properly set 'fastify-plugin'

README.md, help/start.txt, start.js, test/start.js
Added support for PORT env variable when present.
Issue #87
=> added PORT env var

.gitignore, README.md, fork.js, help/start.txt, lib/watch/constants.js, lib/watch/fork.js, lib/watch/index.js, package.json, start.js, test/start.js
* added watch env var
* change test/start.js
* updated help text
=> added watch env var (#91)

generate.js, test/generate.js
=> Set the default logger level to INFO in the template

README.md, generate.js, test/generate.js
=> Remove linter task from the generated code

README.md, package.json, start.js, test/data/rejection.js, test/start.js
See https://github.com/mcollina/make-promises-safe for why.
=> Added make-promises-safe

lib/watch/index.js
=> Make sure to restart after change on app crash

lib/watch/fork.js, lib/watch/index.js
=> Make cli errors red color

.travis.yml, package.json, test/start.js
Fixes #112 
cc @mcollina looks like `CRLF/LF`
=> Testing windows on travis

README.md, help/generate.txt, help/help.txt
=> Update generate help text

generate.js, test/generate.js
Fixes #124 
Although it does not seem to create a problem (at least for me), it's a nicer way.
=> Simplify testing script

start.js
=> Fix: wrong parameter with yargs-parser

README.md, args.js, start.js, test/args.js
Updates the way args is parsed and used
=> Update arg parsing

README.md, args.js, lib/watch/constants.js, lib/watch/index.js, start.js, test/args.test.js, test/watch.test.js
Refactored ignore-watch, fixed some issues, added tests for args.
=> Refactor ignore-watch

package.json, test/generate.test.js
Closes #134 
Not sure if this is the best way to test this so open to suggestions
cc @delvedor
=> Add test for glob pattern

package.json, start.js
Fixes #151 
Not sure how I if I can add a test case for this 
cc @mcollina is there an effective way to test this?
=> Fix ENV parsing

args.js
I think it is useless to use `Object.assgin` there. Is this necessary?
=> fix: useless code delete

generate-readme.js, test/generate-readme.test.js, test/plugindir/package.json, test/plugindir/plugin.js
- add test case for `generator-readme.js`
=> Testcase added

package.json
[dotenv 8 drop node 6](https://github.com/motdotla/dotenv/blob/HEAD/CHANGELOG.md)
Closes #174 and #171
=> greenkeeper ignore

package.json
=> ignore chokidar major and update dep

package.json
Closes #177 
They dropped Node 6 in v3
=> ignore update-notifier

package.json
=> chore(package): update sinon to version 7.3.2

generate.js
=> chore: simplify generate code

start.js, test/start.test.js
make readable for warn and error
=> chore: Make stop more readable

args.js, help/start.txt, start.js, test/args.test.js, test/data/custom-logger.js, test/start.test.js
=> feat: add support for customizing logger configuration

package.json
=> fix(package): update yargs-parser to version 16.0.0

package.json
=> chore(package): update sinon to version 7.5.0

package.json, start.js, util.js
Removes update-notifier for good. I don't think we need this.
Fixes #219
=> Remove update-notifier

package.json
=> chore greenkeeper ignore sinon

.taprc, .travis.yml, lib/watch/index.js, package.json, test/generate.test.js, test/start.test.js
This is unfortunately needed to solve all the flow of security vulnerabilities coming in.
This is going to be semver-major.
Fixes: https://github.com/fastify/fastify-cli/issues/229
=> updated dependencies

generate.js, templates/app-ts/__gitignore, test/generate-typescript.test.js
As discussed in [these](https://github.com/fastify/fastify-cli/issues/131#issuecomment-630192417) comments there were a few fixes needed in the typescript template.
=> fix(#131): added dist folder to gitignore, fixed start script

package.json, test/start.test.js
Basically same as https://github.com/fastify/fastify-cli/pull/236 using fixed pino-colada version
=> Fix pretty print of logs with -P option

package.json, start.js, templates/app/app.js
=> pino colada bug fix

lib/watch/fork.js, print-routes.js, start.js, test/print-routes.test.js, test/start.test.js
=> Migrate to async/await

README.md, generate.js, test/generate.test.js
=> add --integrate flag for fastify generate

templates/app/routes/README.md
=> fix: typo in routes/README

print-routes.js, test/print-routes.test.js
Fixes: https://github.com/fastify/fastify-cli/issues/258
I've added a test though it may be flaky so I'm not sure we want it.
=> Fix fastify routes command

lib/watch/fork.js, test/start.test.js
=> Fix watch test

generate.js, templates/app-ts/tsconfig.json, test/generate-typescript.test.js
=> refactor: use fastify-tsconfig in ts template (#273)

templates/app/__gitignore
=> Do not ignore js files in template gitignore

.dependabot/config.yml, .github/dependabot.yml, .github/workflows/test.yml
=> chore: add dependabot auto merge

.github/workflows/test.yml, args.js, examples/.env, examples/plugin-with-env.js, lib/watch/index.js, print-routes.js, start.js, test/args.test.js, test/start.test.js
Reload the environment when the app restarts in watch mode. Haven't added any tests yet as there are none around watch mode. I would like to validate the idea before spending time testing this, which is not straightforward.
=> feat: reload env when watch restarts the application

package.json, templates/app-ts/src/app.ts, test/templates/app-ts.test.ts
Also includes tests both for compilation and for trying to run the app from app-ts.
refs #303
- [] documentation is changed or added
=> Fix TS compilation error.

package.json, start.js, templates/eject-ts/server.ts, templates/eject/server.js, test/graceful-shutdown.test.js
Issue link: https://github.com/fastify/fastify-cli/issues/317
=> feat: added graceful shutdown (#317) 

README.md, templates/app-ts/src/routes/README.md, templates/app/routes/README.md
Since services directory is now routes.
=> Updated services to routes

README.md
Updates the docs to address issue no. [338](https://github.com/fastify/fastify-cli/issues/338).
=> docs(readme): update migration-out section with the latest eject template code

docs.js
=> add code to check a file

README.md
=> docs: fix number of tasks

generate.js, templates/app-ts/__taprc, templates/app-ts/test/helper.ts, test/generate-typescript.test.js, test/generate.test.js
Fixes #320 
@fox1t 
I did not add `esModuleInterop: true` to `tsconfig.test.json` because changing the import of tap makes it not necessary.
Do you think it is a good practice to add it anyway?
=> fix: fixed test script in typescript template project

.taprc, package.json, templates/plugin/.taprc, test/eject-ts.test.js, test/eject.test.js, test/generate-plugin.test.js, test/generate-typescript.test.js, test/generate.test.js, test/graceful-shutdown.test.js, test/start.test.js
=> chore(deps): bump tap from 14 to 15.0.9

test/start.test.js
=> await close all the time

.github/workflows/ci.yml
=> ci: add nodejs 16 to matrix

generate.js, test/generate-typescript.test.js
Fixes https://github.com/fastify/fastify-cli/issues/377
While using Node v16 or any version above 15, all tests should pass in a newly generated TS project 
`tap` docs on using it with Typescript https://node-tap.org/docs/using-with/#using-tap-with-typescript
=> Bugfix - Fix tap tests in node v15+

README.md
- Adds documentation to `README.md `regarding `fastify-cli` interaction with Docker containers.
resolves https://github.com/fastify/fastify-cli/issues/398
=> docs: add container address info

templates/app-ts/src/routes/example/index.ts
Thank you for such a nice framework :tada:
I just added whitespace after an equal.
- [] tests and/or benchmarks are included
=> chore: add whitespace

README.md
=> docs: add logging module option to readme

templates/app-ts/src/plugins/README.md, templates/app-ts/src/routes/README.md, templates/app/plugins/README.md, templates/app/routes/README.md
- [ x] run `npm run test`
- [ x] documentation is changed or added
- [ x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
=> docs: update plugins guides' link to correct path

templates/eject-ts/server.ts
Also remove `"use strict";` as that is unnecessary in TypeScript.
=> Fix error from eject-ts generated server.ts

README.md, package.json, start.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
Closes #482
=> Use pino-pretty in favor of pino-colada

package.json, test/start.test.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
=> update to fastify v4.0.0

examples/plugin.js, package.json, start.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
Ref: https://github.com/fastify/fastify-cli/pull/499#issuecomment-1152929585
=> Drop pump, remove unneeded loglevel settings

generate-plugin.js, generate.js, test/generate-plugin.test.js, test/generate-typescript.test.js
=> Fix-457: TS Testing pattern fix

start.js
=> Fix deprecation warning when using --socket <path>

lib/watch/index.js
=> fix unreachable if-block

lib/watch/index.js, package.json, test/generate-plugin.test.js, test/generate-typescript.test.js, test/generate.test.js, test/print-routes.test.js, test/start.test.js
This fixes tests that were not passing on master, improved tests to better match behavior and also fix the regression introduced in https://github.com/fastify/fastify-cli/pull/511 described in https://github.com/fastify/fastify-cli/issues/518 and https://github.com/fastify/fastify-cli/issues/513 and https://github.com/fastify/fastify-cli/pull/515.
I will push up a regression test asap, but I want to validate these changes pass in CI here at this point. 
Fixes #513.
Fixes #518.
=> Fix watch regression

README.md
- Added available commands in Fastify-CLI in README.ms which is used to generate server.js file so user can run standalone application and can do the necessary changes to server file independently.
- [++] documentation is changed or added
=> Updated README.md to add available commands in CLI

package.json, templates/app-ts/src/plugins/sensible.ts
Signed-off-by: Matteo Collina <hello@matteocollina.com>
=> Updates @fastify/sensible v5

test/print-routes.test.js, test/start.test.js
=> simplify regex in unit tests

cli.js, test/cli.test.js
=> feat: support a help flag

templates/app-ts/src/app.ts, templates/app/app.js
Clarify how to use options. Someone like I don't read carefully and forgot about `--options`.
And everyone finally has to add options and they don't need re-read documentation about how to use it.
=> Add comment how to use options.

templates/app-esm/app.js
Addendum to #550. Added the options also into the ESM template
=> Adding option also for ESM template

help/start.txt
Improve help for command fastify start --help
- added doc for option --debug
- added doc for option --debugPort
The README.md was already updated with this info
=> Improve start help #561

generate.js
=> Replace pino-colada in help messages with pino-pretty

test/generate-esm.test.js, test/generate-plugin.test.js, test/generate-typescript-esm.test.js, test/generate-typescript.test.js, test/generate.test.js
See https://github.com/fastify/fastify/pull/5057
=> test: optimize split params

.github/workflows/ci.yml
=> drop old nodes

generate-plugin.js, suite-runner.js, templates/plugin/test/index.test-d.ts, test/generate-plugin.test.js
=> fix generate plugin

generate.js
=> remove unused devDep @types/tap

package.json, test/esm/data/custom-logger.cjs, test/esm/package.json, test/esm/util.test.js, util.js
Fixes https://github.com/fastify/fastify-cli/issues/678
=> fix: require doesn't work in esm projects

templates/app/routes/README.md
=> Fix(templates) fix typo

templates/eject-esm/server.js, templates/eject-ts/server.ts, templates/eject/server.js
=> fix: removes async from callback-based onClose hooks

package.json, templates/app-ts-esm/src/plugins/sensible.ts, templates/app-ts/src/plugins/sensible.ts
=> Bump to Fastify v5

help/start.txt, templates/eject-ts/server.ts
=> style: remove trailing whitespace
